CIN-06064 - Removed URL param logic during login that is now handled by the Angular SDK
cinchy-co/meta-forms-app-experience pull request #166
Opened 2023-09-05 14:12 UTC by bibincinchy

CIN-06064 - Removed URL param logic during login that is now handled by the Angular SDK

2023-09-05 15:02 UTC, DAquilinaCinchy requested changes
In the CinchyDynamicFormsComponent, there is a condition on line 310 that was included in the case of a queryParam/session mismatch. Please correct that condition and confirm that the behaviour of the loadForm function remains consistent.

Current path:

```
if (this.rowId) {
  if (!selectedLookupRecord) {
    // deselect record
  }
  else {
    // load record
  }
}
```

Correct:

```
if (selectedLookupRecord) {
  // load record
}
```

2023-09-11 13:46 UTC, bibincinchy commented on src/app/app.component.ts
done

2023-09-11 14:54 UTC, DAquilinaCinchy submitted a review, later dismissed

2023-09-11 14:54 UTC, DAquilinaCinchy commented on src/app/app.component.ts
> +      return idAsNumber;
Please indent this by one more level

2023-09-11 15:20 UTC, bibincinchy commented on src/app/dynamic-forms/cinchy-dynamic-forms.component.ts
>                // This may occur if the rowId is not provided in the queryParams, but one is available in the session
done

2023-09-11 15:20 UTC, bibincinchy commented on src/app/app.component.ts
> +      return idAsNumber;
done

2023-09-11 16:32 UTC, merged